import { InventoryEntry, Product } from './types';

export const calculateConsumption = (
  openingEntries: InventoryEntry[],
  closingEntries: InventoryEntry[],
  products: Product[]
) => {
  return products.map((product) => {
    const opening = openingEntries
      .flatMap((e) => e.items)
      .filter((i) => i.productId === product.id)
      .reduce((acc, curr) => acc + curr.quantity, 0);

    const closing = closingEntries
      .flatMap((e) => e.items)
      .filter((i) => i.productId === product.id)
      .reduce((acc, curr) => acc + curr.quantity, 0);

    const usage = opening - closing;
    
    return {
      productId: product.id,
      productName: product.name,
      opening,
      closing,
      usage: usage > 0 ? usage : 0,
      mismatch: usage < 0 ? Math.abs(usage) : 0, // Negative usage means more stock than started?
    };
  });
};

export const generateWhatsAppReport = (data: any) => {
  const { date, consumption, lowStock, electricity } = data;
  
  let report = `*Daily Restaurant Report - ${date}*\n\n`;
  
  report += `*Stock Usage Summary:*\n`;
  consumption.slice(0, 10).forEach((item: any) => {
    report += `- ${item.productName}: Used ${item.usage}\n`;
  });

  if (lowStock.length > 0) {
    report += `\n*⚠️ Low Stock Alerts:*\n`;
    lowStock.forEach((item: string) => {
      report += `- ${item}\n`;
    });
  }

  report += `\n*Electricity Reading:*\n- ${electricity} units`;
  
  report += `\n\n_Generated by Inventory Pro_`;
  
  return report;
};
